name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - if: ${{ startsWith(matrix.os, 'ubuntu') }}
      name: Install Khiva on Linux
      run: |
        cd /tmp

        sudo apt-get update && sudo apt-get install libboost-all-dev libeigen3-dev

        wget -q https://arrayfire.s3.amazonaws.com/3.8.0/ArrayFire-v3.8.0_Linux_x86_64.sh
        chmod +x ./ArrayFire-v3.8.0_Linux_x86_64.sh
        ./ArrayFire-v3.8.0_Linux_x86_64.sh --include-subdir --prefix=/opt
        echo /opt/arrayfire/lib64 | sudo tee /etc/ld.so.conf.d/arrayfire.conf
        sudo ldconfig

        git clone --recursive --branch v0.5.0 https://github.com/shapelets/khiva
        cd khiva
        mkdir build
        cd build
        cmake .. -DKHIVA_USE_CONAN=OFF -DKHIVA_BUILD_TESTS=OFF -DKHIVA_BUILD_BENCHMARKS=OFF -DKHIVA_BUILD_JNI_BINDINGS=OFF
        make -j4
        sudo make install
        sudo ldconfig
    - if: ${{ startsWith(matrix.os, 'macos') }}
      name: Install Khiva on Mac
      run: |
        brew update
        brew unlink gcc@8
        brew unlink gcc@9
        brew install khiva
    - run: bundle exec rake test
